yolo_test/config/routes.rb
Rails.application.routes.draw do
  get '/static_pages/home', to: 'static_pages#home'
  get '/message/:user_entry', to: 'message#show', as: 'message_show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

yolo_test/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

yolo_test/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

yolo_test/app/controllers/message_controller.rb
class MessageController < ApplicationController
  def show
    puts "$" * 60
    puts "Voici le message de l'URL :"
    puts  params[:user_entry]
    puts "$" * 60
  end
end

yolo_test/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    puts "$" * 60 #ça affiche une ligne de 60 symboles $ facilement visible dans le terminal
    puts params #tu sais que params doit s'afficher entre les 2
    puts "$" * 60
  end
end

yolo_test/app/helpers/application_helper.rb
module ApplicationHelper
end

yolo_test/app/helpers/message_helper.rb
module MessageHelper
end

yolo_test/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

yolo_test/app/views/message/show.html.erb
<h1>Message#show</h1>
<p>Find me in app/views/message/show.html.erb</p>
<%= link_to "clique ici", static_pages_home_path %>

yolo_test/app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>
<%= link_to "clique ici", message_show_path(@user_entry) %>